kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dexter
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
  kind: managed
  diskEncryptionSetID: "/subscriptions/5XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/bankapp-rg/providers/Microsoft.Compute/diskEncryptionSets/bankapp-aks-des"
