apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dexter
provisioner: ebs.csi.aws.com    
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
  kmsKeyId: arn:aws:kms:us-east-2:02XXXXXXXXX6:key/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
